// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAspwQasoMBwcghqSDyvfxwnKDkFEpUM',
    appId: '1:995531465114:web:b6851290782b75797bda23',
    messagingSenderId: '995531465114',
    projectId: 'unitrack-89060',
    authDomain: 'unitrack-89060.firebaseapp.com',
    storageBucket: 'unitrack-89060.firebasestorage.app',
    measurementId: 'G-B6B0JL22PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRdTR8M9dmM5DJlbnLBCpgE0b7ijBieuM',
    appId: '1:995531465114:android:c2e11e1cf323ff667bda23',
    messagingSenderId: '995531465114',
    projectId: 'unitrack-89060',
    storageBucket: 'unitrack-89060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2FFDXLT0jgqPr2J35RA1hQdUdPJI0jA',
    appId: '1:995531465114:ios:495a64c2a33ba23b7bda23',
    messagingSenderId: '995531465114',
    projectId: 'unitrack-89060',
    storageBucket: 'unitrack-89060.firebasestorage.app',
    iosBundleId: 'com.example.unitrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2FFDXLT0jgqPr2J35RA1hQdUdPJI0jA',
    appId: '1:995531465114:ios:495a64c2a33ba23b7bda23',
    messagingSenderId: '995531465114',
    projectId: 'unitrack-89060',
    storageBucket: 'unitrack-89060.firebasestorage.app',
    iosBundleId: 'com.example.unitrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKAspwQasoMBwcghqSDyvfxwnKDkFEpUM',
    appId: '1:995531465114:web:83a1a0f7cfa86be47bda23',
    messagingSenderId: '995531465114',
    projectId: 'unitrack-89060',
    authDomain: 'unitrack-89060.firebaseapp.com',
    storageBucket: 'unitrack-89060.firebasestorage.app',
    measurementId: 'G-YY706N152N',
  );
}
